### ISSUE TITLE
Example 2 arrow keys don't move camera position

### ISSUE THREAD

**Issue by mtdowling** [2dengine/love.scene#6] opened 2024-07-17 01:53 UTC
Using arrow keys to move the camera around with example2/ doesn't actually move the camera position.

**Comment by 2dengine** [comment] 2024-07-17 09:11
Hello and thank you for trying out love.scene.
I can confirm that example2 does not work.
Upon further investigation, I found that the example was broken after a recent change to the interface.
Please note that this issue is not a bug with the library, it is just that the example was out of date.
I have just pushed a fixed to the repository.
Thank you for the feedback!

**Closed** 2024-07-18 01:47 UTC
